version: '2'
services:
  db:
    image: postgres:17
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo18:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "11018:8069"
      - "21018:8072" # live chat
    tty: true
    env_file:
      - .env
    environment:
      - DEV_MODE=1
      - LIST_DB=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo18@2024
      - DB_DATABASE=postgres
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      # Mount for development - auto-reload
      - ./addons:/opt/odoo/addons
      - ./etc/odoo.conf:/etc/odoo/odoo.conf
    restart: always             # run as a service
    